### ISSUE TITLE
Dezimal Punkt stimmt nicht 

### ISSUE THREAD

**Issue by ralf66-thomas** [Phrytes/COVID19_RKI_Germany#2]
Leider stimmt der Dezimal-Punkt in dem File RKI_Covid19_ALL.csv für die Spalte Anzahl nicht.

**Comment by Phrytes** [comment]
Thanks! I didn't use the data by myself (yet!), but I will fix this. However, soon I'll switch to a different way of getting the data using the API: https://github.com/Phrytes/COVID19_RKI_Germany/issues/1

**Comment by Phrytes** [comment]
This should be fixed right now. If you encounter any problems, feel free to create a new issue.
